// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimulationsServiceClient is the client API for SimulationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationsServiceClient interface {
	Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error)
}

type simulationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationsServiceClient(cc grpc.ClientConnInterface) SimulationsServiceClient {
	return &simulationsServiceClient{cc}
}

func (c *simulationsServiceClient) Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error) {
	out := new(SimulateResponse)
	err := c.cc.Invoke(ctx, "/public.v1.SimulationsService/Simulate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationsServiceServer is the server API for SimulationsService service.
// All implementations must embed UnimplementedSimulationsServiceServer
// for forward compatibility
type SimulationsServiceServer interface {
	Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error)
	mustEmbedUnimplementedSimulationsServiceServer()
}

// UnimplementedSimulationsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSimulationsServiceServer struct {
}

func (UnimplementedSimulationsServiceServer) Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simulate not implemented")
}
func (UnimplementedSimulationsServiceServer) mustEmbedUnimplementedSimulationsServiceServer() {}

// UnsafeSimulationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationsServiceServer will
// result in compilation errors.
type UnsafeSimulationsServiceServer interface {
	mustEmbedUnimplementedSimulationsServiceServer()
}

func RegisterSimulationsServiceServer(s grpc.ServiceRegistrar, srv SimulationsServiceServer) {
	s.RegisterService(&SimulationsService_ServiceDesc, srv)
}

func _SimulationsService_Simulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationsServiceServer).Simulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.v1.SimulationsService/Simulate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationsServiceServer).Simulate(ctx, req.(*SimulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationsService_ServiceDesc is the grpc.ServiceDesc for SimulationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "public.v1.SimulationsService",
	HandlerType: (*SimulationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simulate",
			Handler:    _SimulationsService_Simulate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulations.proto",
}
