/* eslint-disable */
/*Generated by GenDocu.com*/
// package: public.v1
// file: maps.proto

var maps_pb = require("./maps_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var MapsService = (function () {
  function MapsService() {}
  MapsService.serviceName = "public.v1.MapsService";
  return MapsService;
}());

MapsService.Geocode = {
  methodName: "Geocode",
  service: MapsService,
  requestStream: false,
  responseStream: false,
  requestType: maps_pb.GeocodeRequest,
  responseType: maps_pb.GeocodeResponse
};

exports.MapsService = MapsService;

function MapsServiceClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

MapsServiceClient.prototype.geocode = function geocode(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(MapsService.Geocode, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

exports.MapsServiceClient = MapsServiceClient;

