/* eslint-disable */
/*Generated by GenDocu.com*/
// package: public.v1
// file: organizations.proto

import * as organizations_pb from "./organizations_pb";
import {grpc} from "@improbable-eng/grpc-web";

type OrganizationsServiceGetOrganization = {
  readonly methodName: string;
  readonly service: typeof OrganizationsService;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof organizations_pb.GetOrganizationRequest;
  readonly responseType: typeof organizations_pb.GetOrganizationResponse;
};

export class OrganizationsService {
  static readonly serviceName: string;
  static readonly GetOrganization: OrganizationsServiceGetOrganization;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class OrganizationsServiceClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  getOrganization(
    requestMessage: organizations_pb.GetOrganizationRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: organizations_pb.GetOrganizationResponse|null) => void
  ): UnaryResponse;
  getOrganization(
    requestMessage: organizations_pb.GetOrganizationRequest,
    callback: (error: ServiceError|null, responseMessage: organizations_pb.GetOrganizationResponse|null) => void
  ): UnaryResponse;
}

