/* eslint-disable */
/*Generated by GenDocu.com*/
// package: public.v1
// file: simulations.proto

import * as jspb from "google-protobuf";
import * as google_protobuf_timestamp_pb from "google-protobuf/google/protobuf/timestamp_pb";
import * as entities_pb from "./entities_pb";

export class SimulateRequest extends jspb.Message {
  clearDestinationsList(): void;
  getDestinationsList(): Array<entities_pb.Delivery>;
  setDestinationsList(value: Array<entities_pb.Delivery>): void;
  addDestinations(value?: entities_pb.Delivery, index?: number): entities_pb.Delivery;

  hasSource(): boolean;
  clearSource(): void;
  getSource(): entities_pb.Address | undefined;
  setSource(value?: entities_pb.Address): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): SimulateRequest.AsObject;
  static toObject(includeInstance: boolean, msg: SimulateRequest): SimulateRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: SimulateRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SimulateRequest;
  static deserializeBinaryFromReader(message: SimulateRequest, reader: jspb.BinaryReader): SimulateRequest;
}

export namespace SimulateRequest {
  export type AsObject = {
    destinationsList: Array<entities_pb.Delivery.AsObject>,
    source?: entities_pb.Address.AsObject,
  }
}

export class SimulateResponse extends jspb.Message {
  hasId(): boolean;
  clearId(): void;
  getId(): string;
  setId(value: string): void;

  getTotal(): number;
  setTotal(value: number): void;

  hasExpectedDeliveryUntil(): boolean;
  clearExpectedDeliveryUntil(): void;
  getExpectedDeliveryUntil(): google_protobuf_timestamp_pb.Timestamp | undefined;
  setExpectedDeliveryUntil(value?: google_protobuf_timestamp_pb.Timestamp): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): SimulateResponse.AsObject;
  static toObject(includeInstance: boolean, msg: SimulateResponse): SimulateResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: SimulateResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SimulateResponse;
  static deserializeBinaryFromReader(message: SimulateResponse, reader: jspb.BinaryReader): SimulateResponse;
}

export namespace SimulateResponse {
  export type AsObject = {
    id: string,
    total: number,
    expectedDeliveryUntil?: google_protobuf_timestamp_pb.Timestamp.AsObject,
  }
}

